### ISSUE TITLE
error_push: dead 'from jarvis import selfhost' import silently kills error rollup forwarding on develop

### ISSUE THREAD

**Issue by kavin-114** [aerele/jarvis#533]
## The defect

`jarvis/error_push.py:60` still does:

```python
from jarvis import selfhost
if selfhost.is_self_hosted():
```

but `9f8d984a chore: remove self-hosted deployment support` **deleted `jarvis/selfhost.py`**. Verified on `upstream/develop` today: the module is gone, and this is the **only** surviving reference to it in `jarvis/*.py`.

So `push_error_rollup` raises `ModuleNotFoundError` on every invocation.

## Why it is silent, and why that is the worst part

The import sits inside that function's own broad `try / except Exception`, so the failure never surfaces. The `*/5` scheduler entry raises every tick and degrades to `_log_push_failure_throttled()`.

Net effect: **error rollup forwarding to admin is dead on `develop` with no visible symptom.** Nothing alerts, nothing is obviously broken, and the feature that exists specifically to make failures visible is itself failing invisibly. It would likely have gone unnoticed until someone asked why admin had stopped receiving tenant errors.

## How it was found

Not by a test. It surfaced while fixing PR #522, whose CI went red with `AttributeError: module 'jarvis' has no attribute 'selfhost'` from the same commit. A repo-wide grep for the deleted module then turned this up as the last straggler. No test covers this path, which is why `9f8d984a` merged clean.

## Fix

Jarvis is managed-only now, so the self-host branch is unreachable, not merely untested. Delete the import and the guard rather than replacing it with a stub.

While there, consider whether that broad `except Exception` should distinguish "the push failed" from "this code cannot run at all". A `ModuleNotFoundError` swallowed by a handler meant for network failures is what let this hide.

## Acceptance

- No reference to `jarvis.selfhost` remains anywhere in the app.
- `push_error_rollup` completes and actually forwards to admin on a managed site.
- A test covers the scheduled path, so the next removal of a shared module cannot silently disable it again.

## Related

Same root commit as the semantic conflicts on PRs #520 and #522. Both were caught only because CI ran against the merge result. This one had no test to catch it.

**Comment by kavin-114** [comment]
Fixed on `develop` by **8f317a28** "fix(chat): revive the error phone-home killed by the selfhost-module deletion".

Verified against `upstream/develop`:
- `jarvis/error_push.py` still exists and `push_error_rollup()` is intact at line 57.
- **Zero** occurrences of `from jarvis import selfhost` remain in the file.

The scheduled `*/5` entry no longer raises `ModuleNotFoundError` into its own broad `except Exception`, so error rollup forwarding to admin is live again rather than silently dead.
